export { default as Home } from "./home/index"
export { default as LogIn } from "./auth/login"
export { default as SignUp } from "./auth/signup"
export { default as Profile } from "./profile/index"
export { default as PostDetail } from "./post/postDetail"
export { default as AddPost } from "./post/addPost"